#
# Module manifest for module 'PwshDocker'
#
# Generated by: michael
#
# Generated on: 5/16/2020
#

@{

# Script module or binary module file associated with this manifest.
RootModule = './PwshDocker.psm1'

# Version number of this module.
ModuleVersion = '0.0.1'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '7b42da90-2d3b-43ca-80a7-dd8edd8d3805'

# Author of this module
Author = 'michael'

# Copyright statement for this module
Copyright = '(c) michael. All rights reserved.'

# Description of the functionality provided by this module
 Description = 'PwshDocker provides a PowerShell way to interact with Docker!'

# Minimum version of the PowerShell engine required by this module
 PowerShellVersion = '6.0'

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = '*'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = '*'

}